services:
  # Laravel application service
  hr_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_app
    volumes:
      - ./hr_service:/var/www/html
      - ./hr_service:/var/www/hr_service
    networks:
      - mcp_network
    depends_on:
      redis:
        condition: service_healthy

  hub_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hub_app
    volumes:
      - ./hub_service:/var/www/html
      - ./hub_service:/var/www/hub_service
    networks:
      - mcp_network
    depends_on:
      redis:
        condition: service_healthy

  hub_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hub_consumer
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    volumes:
      - ./hub_service:/var/www/html
    networks:
      - mcp_network
    depends_on:
      - rabbitmq
      - hub_app
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mcp_rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ server
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mcp_network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: mcp_nginx
    ports:
      - "8080:80"
    volumes:
      - ./hr_service:/var/www/hr_service
      - ./hub_service:/var/www/hub_service
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mcp_network
    depends_on:
      - hr_app
      - hub_app

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: mcp_redis
    restart: unless-stopped
    networks:
      - mcp_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: mcp_mysql
    restart: unless-stopped
    ports:
      - "3310:3306" # open for local tools
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mcp_user
      MYSQL_PASSWORD: mcp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mcp_network

networks:
  mcp_network:
    external: true

volumes:
  redis_data:
  db_data:
  rabbitmq_data:
