server {
    listen 80;
    server_name hr.localhost;

    root /var/www/hr_service/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass hr_app:9000;
        fastcgi_index index.php;

        # Use matching paths mounted in both nginx and php-fpm containers.
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    listen 80;
    server_name hub.localhost;

    root /var/www/hub_service/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass hub_app:9000;
        fastcgi_index index.php;

        # Use matching paths mounted in both nginx and php-fpm containers.
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}